//
//  ReportsViewController.swift
//  CERT
//
//  Created by student on 4/18/22.
//

import UIKit
import FirebaseAuth
import Firebase
import FirebaseDatabase

class ReportsViewController: UIViewController, UITableViewDelegate, UITableViewDataSource
{

var reportsArray : [Dictionary<String, Any>] = []
    
    var reports = [["Title : Fire ","Incident Location : San Francisco","https://firebasestorage.googleapis.com:443/v0/b/cert-db.appspot.com/o/imageReports%2FFBDF507A-F280-4537-8359-F61A3CC49EC3?alt=media&token=e713a194-3298-4f43-abf8-9f8db465c532","Type Of Incident : EarthQuake ", "Casuality Impact Level","Red:1 Green:2 Yellow:3 Black:4","Fire Hazard Imapct : Medium","Structural Damage Impact : Medium","Hazmat Type : Gas"],["Title : Fire Accident ","Incident Location : San Francisco","https://firebasestorage.googleapis.com:443/v0/b/cert-db.appspot.com/o/imageReports%2FFBDF507A-F280-4537-8359-F61A3CC49EC3?alt=media&token=e713a194-3298-4f43-abf8-9f8db465c532","Type Of Incident : EarthQuake ", "Casuality Impact Level","Red:0 Green:5 Yellow:1 Black:0","Fire Hazard Imapct : Low","Structural Damage Impact : Medium","Hazmat Type : Gas"],["Title : Floods ","Incident Location : California","","Type Of Incident : Floods ", "Casuality Impact Level","Red:5 Green:4 Yellow:3 Black:2","Fire Hazard Imapct : Low","Structural Damage Impact : Medium","Hazmat Type : Electricity"],["Title : Fire ","Incident Location : Jones St","","Type Of Incident : Floods ", "Casuality Impact Level","Red:5 Green:0 Yellow:3 Black:0","Fire Hazard Imapct : Low","Structural Damage Impact : Medium","Hazmat Type : Solid"],["Title : Tornado ","Incident Location : San Francisco","","Type Of Incident : Tornado ", "Casuality Impact Level","Red:2 Green:3 Yellow:2 Black:1","Fire Hazard Imapct : Minor","Structural Damage Impact : Medium","Hazmat Type : Fluid"],["Title : Floods ","Incident Location : Colden Hall University Dr","","Type Of Incident : Floods ", "Casuality Impact Level","Red:10 Green:9 Yellow:0 Black:9","Fire Hazard Imapct : Low ","Structural Damage Impact : Medium","Hazmat Type : Chemical"],["Title : Fire Accident ","Incident Location : San Francisco","","Type Of Incident : Storm ", "Casuality Impact Level","Red:9 Green:7 Yellow:8 Black:10","Fire Hazard Imapct : Low ","Structural Damage Impact : Medium","Hazmat Type : Fluid"],["Title : Fire Accident ","Incident Location : San Francisco","https://firebasestorage.googleapis.com/v0/b/cert-db.appspot.com/o/imageReports%2FJPEG_20220322_212915.jpg?alt=media&token=bb2b7a91-a34a-470b-b228-dbff86e06046","Type Of Incident : Storm ", "Casuality Impact Level","Red:9 Green:7 Yellow:8 Black:10","Fire Hazard Imapct : Low ","Structural Damage Impact : Medium","Hazmat Type : Fluid"],["Title : Fire Accident ","Incident Location : San Francisco",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "https://firebasestorage.googleapis.com/v0/b/cert-db.appspot.com/o/imageReports%2FCERTAndroidApp_20220302_230501_711753536752954511.jpg?alt=media&token=d2181eaa-26b7-4672-bfe2-570a438c6c9b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "Type Of Incident : Tornado ",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Casuality Impact Level",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Red:4 Green:4 Yellow:4 Black:4",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Fire Hazard Imapct : Low ",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Structural Damage Impact : Medium",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Hazmat Type : Gas"],["Title : Cooking accident ","Incident Location : 1600 Amphitheatre Pkwy Mountain View",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "https://firebasestorage.googleapis.com/v0/b/cert-db.appspot.com/o/imageReports%2FJPEG_20220322_212915.jpg?alt=media&token=bb2b7a91-a34a-470b-b228-dbff86e06046",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Type Of Incident : Earthquake ",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "Casuality Impact Level",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "Red:4 Green:8 Yellow:4 Black:6",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "Fire Hazard Imapct : Low ",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "Structural Damage Impact : Medium",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "Hazmat Type : Electricity"],["Title : Fire Accident ","Incident Location : San Francisco",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "https://firebasestorage.googleapis.com:443/v0/b/cert-db.appspot.com/o/imageReports%2F5E7DC5A7-69C2-4C50-973A-A1ED610A6506?alt=media&token=088f670b-1553-4758-b6c1-fe6424821fe2",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "Type Of Incident : Tornado ",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Casuality Impact Level",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Red:6 Green:6 Yellow:2 Black:1",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Fire Hazard Imapct : Low ",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Structural Damage Impact : Medium",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Hazmat Type : Fluid"],
                   ["Title : Fire Accident ","Incident Location : Missouri",
                   "https://firebasestorage.googleapis.com/v0/b/cert-db.appspot.com/o/imageReports%2FCERTAndroidApp_20220303_120734_4790145216441346862.jpg?alt=media&token=c94d779c-65cc-4b6c-892d-b181785f14c1",
                   "Type Of Incident : Fire ",
                    "Casuality Impact Level",
                    "Red:10 Green:5 Yellow:20 Black:0",
                    "Fire Hazard Imapct : Low ",
                    "Structural Damage Impact : Medium",
                    "Hazmat Type : None"],["Title : Fire Accident ","Incident Location : San Francisco",
                                           "https://firebasestorage.googleapis.com:443/v0/b/cert-db.appspot.com/o/imageReports%2F55CE6473-4C5B-4CAA-8976-CA60E3B679D5?alt=media&token=39b9ce64-0327-4cf0-ad98-2badafe2a26e",
                                           "Type Of Incident : EarthQuake ",
                                            "Casuality Impact Level",
                                            "Red:2 Green:4 Yellow:3 Black:6",
                                            "Fire Hazard Imapct : Low ",
                                            "Structural Damage Impact : Medium",
                                            "Hazmat Type : Major"],
                   ["Title : san ","Incident Location : Maryville",
                   "",
                   "Type Of Incident : Tornadoes ",
                    "Casuality Impact Level",
                    "Red:2 Green:2 Yellow:23 Black:2",
                    "Fire Hazard Imapct : Low ",
                    "Structural Damage Impact : Medium",
                    "Hazmat Type : fluid"],["Title : rs-1232 ","Incident Location : Frisco",
                                            "",
                                            "Type Of Incident : Thunderstorms ",
                                             "Casuality Impact Level",
                                             "Red:3 Green:2 Yellow:3 Black:2",
                                             "Fire Hazard Imapct : Low ",
                                             "Structural Damage Impact : Medium",
                                             "Hazmat Type : gas"]]

    @IBOutlet weak var reportsTable: UITableView!
    override func viewDidLoad() {
        super.viewDidLoad()

        reportsTable.delegate = self
        reportsTable.dataSource = self
        
//        let db = Firestore.firestore()
//            db.collection("reportsDB").getDocuments{(snapshot ,error) in
//                if error == nil {
//                    for document in snapshot!.documents{
//                        let docdata = document.data()
//                        print("reports data")
//                        print(type(of: docdata))
//                        print(docdata)
//                        self.reportsArray.append(docdata)
//                    }
//                }
//            }
        print("printing reports array in reports controller")
        print(reportsArray)
    }

   func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
       return reports.count
   }
   
   func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
       let cell = reportsTable.dequeueReusableCell(withIdentifier: "reportsCell", for: indexPath)
//       let t = reportsArray[indexPath.row]["title"] as! String
    
//       cell.textLabel?.text = t
       
       let picURL = reports[indexPath.row][2]//just for tests - some random png
           let url = NSURL(string: picURL)
       //let data = NSData(contentsOf: url! as URL)
       cell.textLabel?.text = reports[indexPath.row][0]
       cell.detailTextLabel?.text = reports[indexPath.row][1]
       if let data = NSData(contentsOf: url! as URL)
       {
           cell.imageView?.image = UIImage(data: data as Data)
       }
       else{
           cell.imageView?.image = UIImage(named: "noImage")
       }
       return cell
   }

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        let identifier = segue.identifier
        if identifier == "reportsDataSegue" {
            let segueDestination = segue.destination as! ReportsDataViewController
            segueDestination.data = reports[reportsTable.indexPathForSelectedRow!.row]
        }
    }

}
